
# Gem::Specification for Test-spec-0.4.1.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: test-spec
version: !ruby/object:Gem::Version 
  version: 0.4.1.1
platform: ruby
authors: 
- Christian Neukirchen
autorequire: 
bindir: bin

date: 2008-10-22 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: allison
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: markaby
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: test/spec layers an RSpec-inspired interface on top of Test::Unit, so you can mix TDD and BDD (Behavior-Driven Development).  test/spec is a clean-room implementation that maps most kinds of Test::Unit assertions to a 'should'-like syntax.  This is a fork of the main version to add some features and make things a bit easier for developers.  It grew out of  day to day use at Relevance (http://thinkrelevance.com).
email: chneukirchen@gmail.com
executables: 
- specrb
- specrb
extensions: []

extra_rdoc_files: 
- bin/specrb
- CHANGELOG
- lib/test/spec/dox.rb
- lib/test/spec/focused/collector-extensions.rb
- lib/test/spec/focused/focused.rb
- lib/test/spec/rails_helper.rb
- lib/test/spec/rdox.rb
- lib/test/spec/should-output.rb
- lib/test/spec/version.rb
- lib/test/spec.rb
- README.rdoc
- SPECS
files: 
- bin/specrb
- CHANGELOG
- examples/stack.rb
- examples/stack_spec.rb
- lib/test/spec/dox.rb
- lib/test/spec/focused/collector-extensions.rb
- lib/test/spec/focused/focused.rb
- lib/test/spec/rails_helper.rb
- lib/test/spec/rdox.rb
- lib/test/spec/should-output.rb
- lib/test/spec/version.rb
- lib/test/spec.rb
- Rakefile
- README.rdoc
- ROADMAP
- SPECS
- test/helper.rb
- test/spec_dox.rb
- test/spec_flexmock.rb
- test/spec_focused.rb
- test/spec_mocha.rb
- test/spec_nestedcontexts.rb
- test/spec_new_style.rb
- test/spec_should-output.rb
- test/spec_testspec.rb
- test/spec_testspec_order.rb
- test/test_testunit.rb
- TODO
- Manifest
- test-spec.gemspec
has_rdoc: true
homepage: http://github.com/relevance/test-spec
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Test-spec
- --main
- README.rdoc
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: test-spec
rubygems_version: 1.3.0
specification_version: 2
summary: Relevance fork of Behaviour Driven Development interface for Test::Unit
test_files: 
- test/test_testunit.rb
